# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e109fa2869d913aac5f6a4fd039acfd30f00e2ffffac273767d7ea895f80dddd4dd0f2df7541660eeaac5e8039cff9f2a37931b1f2594e7b0f70ede81845bd4

test:
  secret_key_base: 44409200e71839503b50df07da418780418a82df824529fa3eb805ac939830580570c7c94a0e71d4f294a3eaa17d084f5961b34fa1c4774b4e5bfafacac7d771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
